GitHub action on PR: markdownlint
Libera-Chat/libera-chat.github.io pull request #76
Opened 2021-06-07 16:07 UTC by PriceChild

Part resolves: https://github.com/Libera-Chat/libera-chat.github.io/issues/69

2021-06-07 18:56 UTC, PriceChild commented on .github/workflows/lint.yml
> +          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
@swantzter is https://github.com/PriceChild/libera-chat.github.io/commit/0f83404cbebd3a73acb36039989f900f199419ee what you are looking for?

2021-06-07 19:02 UTC, PriceChild commented on content/_guides/connect.md
> +directly connect to `irc.libera.chat` via Tor; use the following hidden service
I put this in a code block just so the "common name" linter didn't complain about it not being capitalised which I thought was weird for a url. Yes, replacing it with `[irc.Libera.Chat](irc:irc.libera.chat)` is cool. (or keeping capitalisation & adding a rule disable)

Just below, there's the hidden service .onion address which is formatted as a code block. Do you want that as a link too?

I would very much like to make them the same (code blocks, given half already are) just to get the linting merged, then make changes like that later? You're the boss!

2021-06-07 19:07 UTC, PriceChild commented on .github/workflows/lint.yml
> +          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
(The reasoning for me adding either was for caching of the npm install.)

2021-06-07 19:19 UTC, swantzter commented on .github/workflows/lint.yml
> +          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
Yeah that works

2021-06-07 20:20 UTC, glguy commented on content/_guides/connect.md
> +directly connect to `irc.libera.chat` via Tor; use the following hidden service
If we're going to make things clickable IRC URLs, let's always do them as ones that point to TLS, however that works.

2021-06-07 20:33 UTC, PriceChild commented on content/_guides/connect.md
> +directly connect to `irc.libera.chat` via Tor; use the following hidden service
@glguy makes sense, updated my example in comment above with `ircs`.

As discussed elsewhere though, I'd prefer to limit this PR to the minimal changes required to pass linting, using existing styles etc. If we want to change styles (e.g. moving to fenced code blocks, or linkifying all hostnames) then I feel a subsequent and separate PR would be best suited to that.

2021-06-08 17:30 UTC, PriceChild commented on content/_guides/connect.md
> +directly connect to `irc.libera.chat` via Tor; use the following hidden service
Agreed we'll leave these as code blocks for now.

2021-06-08 17:36 UTC, swantzter approved these changes

2021-06-09 20:44 UTC, swantzter requested changes

2021-06-09 20:44 UTC, swantzter commented on .github/workflows/lint.yml
> +      - run: npx markdownlint-cli '**/*.md'
actually, now that we have a packkage.json we might as well move this here to make local dev easier
```suggestion
      - run: npm run markdownlint
```

2021-06-09 20:44 UTC, swantzter commented on package.json
> +  "description": "Libera Chat website",
```suggestion
  "description": "Libera Chat website",
  "scripts": {
    "lint:md": "markdownlint-cli '**/*.md'",
    "lint:md:fix": "npm run lint:md -- --fix"
  },
```

2021-06-09 20:45 UTC, swantzter commented on .github/workflows/lint.yml
> +          node-version: 12
also now taht we ahve a package.json
```suggestion
          node-version: 12
      - run: npm i --prefer-offline
```

2021-06-09 20:51 UTC, swantzter commented on .github/workflows/lint.yml
> +    branches: [ main ]
```suggestion
on: [push, pull_request]
```

2021-06-09 21:03 UTC, merged